#!/usr/bin/env python3
"""Fetch today's menu from U Krkovice and post it to Discord, with a
historical fun-fact about today's date generated by the claude CLI."""

import html
import os
import random
import re
import subprocess
import sys
import unicodedata
import xml.etree.ElementTree as ET
from datetime import datetime
from zoneinfo import ZoneInfo

import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv

MENU_URL = "https://ukrkovice.cz/j%C3%ADdeln%C3%AD-l%C3%ADstek/j%C3%ADdeln%C3%AD-l%C3%ADstek"
TIMEZONE = ZoneInfo("Europe/Prague")

PRAGUE_LATITUDE = 50.0755
PRAGUE_LONGITUDE = 14.4378
STOCK_SYMBOL = "TENX"
STOCK_NAME = "Tenax Therapeutics"

WEATHER_CODES = {
    0: ("Jasno", "☀️"),
    1: ("Skoro jasno", "🌤️"),
    2: ("Polojasno", "⛅"),
    3: ("Zataženo", "☁️"),
    45: ("Mlha", "🌫️"),
    48: ("Mlha s jínovatkou", "🌫️"),
    51: ("Slabé mrholení", "🌦️"),
    53: ("Mrholení", "🌦️"),
    55: ("Vydatné mrholení", "🌦️"),
    56: ("Mrznoucí mrholení", "🌦️"),
    57: ("Vydatné mrznoucí mrholení", "🌦️"),
    61: ("Slabý déšť", "🌧️"),
    63: ("Déšť", "🌧️"),
    65: ("Vydatný déšť", "🌧️"),
    66: ("Mrznoucí déšť", "🌨️"),
    67: ("Vydatný mrznoucí déšť", "🌨️"),
    71: ("Slabé sněžení", "🌨️"),
    73: ("Sněžení", "🌨️"),
    75: ("Vydatné sněžení", "❄️"),
    77: ("Sněhové zrno", "❄️"),
    80: ("Přeháňky", "🌦️"),
    81: ("Silnější přeháňky", "🌦️"),
    82: ("Prudké přeháňky", "⛈️"),
    85: ("Sněhové přeháňky", "🌨️"),
    86: ("Silné sněhové přeháňky", "🌨️"),
    95: ("Bouřka", "⛈️"),
    96: ("Bouřka s kroupami", "⛈️"),
    99: ("Silná bouřka s kroupami", "⛈️"),
}

TRANSIT_STOPS = ["Černý Kůň", "Smíchovské nádraží", "Palmovka", "Lužiny", "Velká Chuchle", "Výtoň"]
TRANSIT_FEEDS = [
    "https://pid.cz/feed/rss-mimoradnosti/",
    "https://pid.cz/feed/rss-vyluky/",
]
TRANSIT_NS = {"content": "http://purl.org/rss/1.0/modules/content/"}

load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))
DISCORD_WEBHOOK_URL = os.environ["DISCORD_WEBHOOK_URL"]


def fetch_menu_items(section_name, item_prefix, price_prefix):
    """Return [(name, description, price), ...] for a menu section, in
    document order, skipping empty placeholder rows."""
    response = requests.get(
        MENU_URL,
        headers={"User-Agent": "Mozilla/5.0 (compatible; claude-good-morning/1.0)"},
        timeout=15,
    )
    response.raise_for_status()
    soup = BeautifulSoup(response.content, "html.parser")

    date_str = None
    menu_date = None
    time_tag = soup.find("time")
    if time_tag:
        date_str = time_tag.get_text(strip=True)
        iso = time_tag.get("datetime")
        if iso:
            try:
                menu_date = datetime.fromisoformat(iso.replace("Z", "+00:00")).date()
            except ValueError:
                pass

    section = soup.find(attrs={"data-framer-name": section_name})
    if section is None:
        return [], date_str, menu_date

    def matches(tag, prefix):
        return tag.name == "div" and tag.get("data-framer-name", "").startswith(prefix)

    name_divs = section.find_all(lambda tag: matches(tag, item_prefix))
    price_divs = section.find_all(lambda tag: matches(tag, price_prefix))

    items = []
    for name_div, price_div in zip(name_divs, price_divs):
        name_tag = name_div.find("h4")
        desc_tag = name_div.find("p")
        price_tag = price_div.find("h4")

        name = name_tag.get_text(strip=True) if name_tag else ""
        desc = desc_tag.get_text(strip=True) if desc_tag else ""
        price = price_tag.get_text(strip=True) if price_tag else ""

        if not name or not price:
            continue
        items.append((name, desc, price))

    return items, date_str, menu_date


DAYPARTS = [
    ("Ráno", 6),
    ("Dopoledne", 9),
    ("Poledne", 12),
    ("Odpoledne", 15),
    ("Večer", 18),
    ("Noc", 21),
]


def fetch_weather():
    response = requests.get(
        "https://api.open-meteo.com/v1/forecast",
        params={
            "latitude": PRAGUE_LATITUDE,
            "longitude": PRAGUE_LONGITUDE,
            "hourly": "temperature_2m,precipitation_probability,weathercode",
            "daily": "temperature_2m_max,temperature_2m_min,precipitation_probability_max,weathercode",
            "timezone": "Europe/Prague",
            "forecast_days": 1,
        },
        timeout=15,
    )
    response.raise_for_status()
    data = response.json()
    daily = data["daily"]
    hourly = data["hourly"]

    description, emoji = WEATHER_CODES.get(daily["weathercode"][0], ("Neznámo", "🌡️"))

    today_str = daily["time"][0]
    hour_index = {t: i for i, t in enumerate(hourly["time"])}

    dayparts = []
    for label, hour in DAYPARTS:
        idx = hour_index.get(f"{today_str}T{hour:02d}:00")
        if idx is None:
            continue
        part_desc, part_emoji = WEATHER_CODES.get(hourly["weathercode"][idx], ("Neznámo", "🌡️"))
        dayparts.append(
            {
                "label": label,
                "emoji": part_emoji,
                "description": part_desc,
                "temp": hourly["temperature_2m"][idx],
                "precip_prob": hourly["precipitation_probability"][idx],
            }
        )

    return {
        "description": description,
        "emoji": emoji,
        "tmax": daily["temperature_2m_max"][0],
        "tmin": daily["temperature_2m_min"][0],
        "precip_prob": daily["precipitation_probability_max"][0],
        "dayparts": dayparts,
    }


def fetch_stock(symbol):
    response = requests.get(
        f"https://query1.finance.yahoo.com/v8/finance/chart/{symbol}",
        headers={"User-Agent": "Mozilla/5.0 (compatible; claude-good-morning/1.0)"},
        timeout=15,
    )
    response.raise_for_status()
    meta = response.json()["chart"]["result"][0]["meta"]
    price = meta["regularMarketPrice"]
    previous_close = meta["previousClose"]
    change = price - previous_close
    change_pct = (change / previous_close) * 100
    return {
        "price": price,
        "previous_close": previous_close,
        "change": change,
        "change_pct": change_pct,
    }


def fetch_name_day(today):
    response = requests.get(
        f"https://svatkyapi.cz/api/day/{today.strftime('%Y-%m-%d')}",
        timeout=15,
    )
    response.raise_for_status()
    return response.json()["name"]


def _strip_html(text):
    text = re.sub(r"<[^>]+>", " ", text)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def _normalize(text):
    decomposed = unicodedata.normalize("NFKD", text)
    return "".join(c for c in decomposed if not unicodedata.combining(c)).lower()


def fetch_transit_alerts(today):
    normalized_stops = [(name, _normalize(name)) for name in TRANSIT_STOPS]

    day_start = int(datetime(today.year, today.month, today.day, tzinfo=TIMEZONE).timestamp())
    day_end = day_start + 86400

    seen_guids = set()
    alerts = []

    for feed_url in TRANSIT_FEEDS:
        response = requests.get(
            feed_url,
            headers={"User-Agent": "Mozilla/5.0 (compatible; claude-good-morning/1.0)"},
            timeout=15,
        )
        response.raise_for_status()
        root = ET.fromstring(response.content)

        for item in root.iter("item"):
            guid = item.findtext("guid") or item.findtext("link") or ""
            if guid in seen_guids:
                continue

            date_from_text = (item.findtext("dateFrom") or "").strip()
            date_to_text = (item.findtext("dateTo") or "").strip()
            date_from = int(date_from_text) if date_from_text else None
            date_to = int(date_to_text) if date_to_text else None

            if date_from is not None and date_from > day_end:
                continue
            if date_to is not None and date_to < day_start:
                continue

            title = item.findtext("title") or ""
            description = _strip_html(item.findtext("description") or "")
            content_encoded = _strip_html(item.findtext("content:encoded", namespaces=TRANSIT_NS) or "")

            haystack = _normalize(f"{title} {description} {content_encoded}")
            matched_stops = [name for name, norm in normalized_stops if norm in haystack]
            if not matched_stops:
                continue

            seen_guids.add(guid)
            alerts.append(
                {
                    "title": title.strip(),
                    "link": item.findtext("link") or "",
                    "date_display": (item.findtext("date") or description).strip(),
                    "matched_stops": matched_stops,
                    "sort_key": date_from or 0,
                }
            )

    alerts.sort(key=lambda a: a["sort_key"])
    return alerts


FUN_FACT_THEMES = [
    "vědy nebo techniky",
    "umění, hudby nebo filmu",
    "sportu",
    "objevů a cestovatelství",
    "vesmíru a astronomie",
    "kultury nebo literatury",
    "vynálezů a technologií",
    "přírody nebo zvířat",
    "architektury nebo stavitelství",
    "každodenního života a kuriozit",
]


def get_fun_fact_from_claude(today):
    """Ask the claude CLI for a fun fact. Returns the text, or None if the
    CLI call fails (e.g. expired OAuth session) so a fallback can kick in."""
    theme = random.choice(FUN_FACT_THEMES)
    prompt = (
        f"Napiš jednu zábavnou a vtipnou zajímavost (1-2 věty, česky) o události "
        f"z historie, která se stala {today.day}. {today.month}. (v kterémkoli roce), "
        f"ideálně z oblasti {theme}. Podej to s humorem, klidně s vtipnou pointou "
        f"nebo odlehčeným komentářem, ať se u toho člověk ráno pousměje. "
        f"Vyhni se tématům druhé světové války a válek obecně, ať jsou zajímavosti "
        f"pestré. Pokud v dané oblasti nic zajímavého nemáš, vyber jakoukoli jinou "
        f"nenásilnou zajímavost k tomuto datu – nikdy neodmítej. Piš pouze samotný "
        f"text zajímavosti, bez úvodu, bez uvozovek."
    )
    try:
        result = subprocess.run(
            # --allowedTools none: whitelist a non-existent tool so no real tools
            # are available. Otherwise the model tries web search, hits a permission
            # block in non-interactive mode, and narrates it into the output.
            ["claude", "-p", prompt, "--model", "claude-haiku-4-5", "--allowedTools", "none"],
            capture_output=True,
            text=True,
            timeout=90,
        )
    except subprocess.TimeoutExpired:
        print("claude CLI fun fact timed out after 90s", file=sys.stderr)
        return None
    fact = result.stdout.strip()
    if result.returncode != 0 or not fact:
        print(
            f"claude CLI fun fact failed (exit {result.returncode}): "
            f"{(result.stderr or result.stdout).strip()[:200]}",
            file=sys.stderr,
        )
        return None
    return fact


def get_fun_fact_from_wikipedia(today):
    """Fallback: pick a historical event for today from the Czech Wikipedia
    'on this day' feed (no API key needed)."""
    response = requests.get(
        f"https://api.wikimedia.org/feed/v1/wikipedia/cs/onthisday/events/"
        f"{today.month:02d}/{today.day:02d}",
        headers={"User-Agent": "wakeup-bot/1.0 (personal Discord good-morning bot)"},
        timeout=15,
    )
    response.raise_for_status()
    events = response.json().get("events", [])
    if not events:
        return None
    event = random.choice(events)
    text = event.get("text", "").strip()
    year = event.get("year")
    if not text:
        return None
    return f"V roce {year}: {text}" if year else text


def get_fun_fact(today):
    fact = get_fun_fact_from_claude(today)
    if fact:
        return fact
    try:
        fact = get_fun_fact_from_wikipedia(today)
        if fact:
            return fact
    except Exception as exc:
        print(f"Wikipedia fun fact fallback failed: {exc}", file=sys.stderr)
    return "(zajímavost se dnes nepodařilo načíst)"


def build_message(soups, mains, date_str, weather, stock, name_day, transit_alerts, fun_fact):
    lines = [f"📅 **Dobré ráno – {date_str}**"]
    if name_day:
        lines.append(f"🎉 Dnes má svátek: **{name_day}**")
    lines.append("")

    # Menu is only added on days U Krkovice actually publishes one (skips weekends).
    if soups or mains:
        lines.append("**🍴 Denní menu U Krkovice**")

        if soups:
            lines.append("**🍲 Polévky**")
            for name, desc, price in soups:
                lines.append(f"• {name} – {desc} – {price}" if desc else f"• {name} – {price}")
            lines.append("")

        if mains:
            lines.append("**🍽️ Denní nabídka**")
            for name, desc, price in mains:
                lines.append(f"• {name} – {desc} – {price}" if desc else f"• {name} – {price}")
            lines.append("")

    lines.append("**🌤️ Počasí (Praha)**")
    if weather:
        lines.append(
            f"{weather['emoji']} {weather['description']}, "
            f"{weather['tmin']:.0f}°C – {weather['tmax']:.0f}°C, "
            f"šance na srážky {weather['precip_prob']:.0f}%"
        )
        for part in weather["dayparts"]:
            lines.append(
                f"• {part['label']}: {part['emoji']} {part['description']}, "
                f"{part['temp']:.0f}°C, srážky {part['precip_prob']:.0f}%"
            )
    else:
        lines.append("(předpověď se nepodařilo načíst)")
    lines.append("")

    lines.append(f"**📈 {STOCK_NAME} (NASDAQ: {STOCK_SYMBOL})**")
    if stock:
        arrow = "📈" if stock["change"] >= 0 else "📉"
        lines.append(
            f"{arrow} ${stock['price']:.2f} "
            f"({stock['change']:+.2f}, {stock['change_pct']:+.2f}%) "
            f"oproti předchozí uzávěrce ${stock['previous_close']:.2f}"
        )
    else:
        lines.append("(cenu se nepodařilo načíst)")
    lines.append("")

    lines.append("**🚇 MHD – vaše zastávky**")
    if transit_alerts is None:
        lines.append("(mimořádnosti se nepodařilo načíst)")
    elif not transit_alerts:
        lines.append("Žádné mimořádnosti na sledovaných zastávkách.")
    else:
        for alert in transit_alerts:
            stops = ", ".join(alert["matched_stops"])
            lines.append(f"• **{stops}** – {alert['title']} ({alert['date_display']})")
    lines.append("")

    lines.append("💡 **Zajímavost o dnešním dni**")
    lines.append(fun_fact)

    message = "\n".join(lines)
    if len(message) > 2000:
        message = message[:1997] + "..."
    return message


def send_to_discord(message):
    response = requests.post(DISCORD_WEBHOOK_URL, json={"content": message}, timeout=15)
    response.raise_for_status()


def main():
    today = datetime.now(TIMEZONE)
    date_str = today.strftime("%-d. %-m. %Y")

    try:
        soups, _, menu_date = fetch_menu_items("Polévky", "Polívka + popis", "Cena polívky")
        mains, _, _ = fetch_menu_items("Denní nabídka", "Denní jídlo + popis", "Cena denního jídla")
        # U Krkovice leaves the last weekday's menu up over the weekend, so an
        # empty menu isn't the signal for "no menu today" — a stale date is.
        # Only show the menu when its own date matches today.
        if menu_date != today.date():
            if menu_date is not None:
                print(
                    f"Menu date {menu_date} != today {today.date()}; omitting stale menu.",
                    file=sys.stderr,
                )
            soups, mains = [], []
    except Exception as exc:
        print(f"Failed to fetch/parse menu: {exc}", file=sys.stderr)
        soups, mains = [], []

    try:
        weather = fetch_weather()
    except Exception as exc:
        print(f"Failed to fetch weather: {exc}", file=sys.stderr)
        weather = None

    try:
        stock = fetch_stock(STOCK_SYMBOL)
    except Exception as exc:
        print(f"Failed to fetch stock price: {exc}", file=sys.stderr)
        stock = None

    try:
        name_day = fetch_name_day(today)
    except Exception as exc:
        print(f"Failed to fetch name day: {exc}", file=sys.stderr)
        name_day = None

    try:
        transit_alerts = fetch_transit_alerts(today)
    except Exception as exc:
        print(f"Failed to fetch transit alerts: {exc}", file=sys.stderr)
        transit_alerts = None

    fun_fact = get_fun_fact(today)
    message = build_message(soups, mains, date_str, weather, stock, name_day, transit_alerts, fun_fact)
    print(message)
    send_to_discord(message)
    print("Posted to Discord successfully.")


if __name__ == "__main__":
    main()
